# Pair Programming Environment

In [17]:
9%3

0

In [26]:
for x in range(1,101):
    if x % 2 ==0:
        even_odd = 'even'
    else:
        even_odd = 'odd'
    if even_odd == 'even' and a:
        further code here

1
is odd
2
3
is odd
4
5
is odd
6
7
is odd
8
9
is odd
10
11
is odd
12
13
is odd
14
is divisable by 14
15
is odd
16
17
is odd
18
19
is odd
20
21
is odd
22
23
is odd
24
25
is odd
26
27
is odd
28
is divisable by 14
29
is odd
30
31
is odd
32
33
is odd
34
35
is odd
36
37
is odd
38
39
is odd
40
41
is odd
42
is divisable by 14
43
is odd
44
45
is odd
46
47
is odd
48
49
is odd
50
51
is odd
52
53
is odd
54
55
is odd
56
is divisable by 14
57
is odd
58
59
is odd
60
61
is odd
62
63
is odd
64
65
is odd
66
67
is odd
68
69
is odd
70
is divisable by 14
71
is odd
72
73
is odd
74
75
is odd
76
77
is odd
78
79
is odd
80
81
is odd
82
83
is odd
84
is divisable by 14
85
is odd
86
87
is odd
88
89
is odd
90
91
is odd
92
93
is odd
94
95
is odd
96
97
is odd
98
is divisable by 14
99
is odd
100

In [30]:
for x in range(1,101):
    print (x)
    if x%2 != 0:
        print("is odd")
    if x%2==0 and x%14==0:
        print("is divisable by 14")
    if x%5==0 and x%2==0:
        print("high five!")
    if x > 30 and x < 45 and x%8==0:
        print("this happens twice")

1
is odd
2
3
is odd
4
5
is odd
6
7
is odd
8
9
is odd
10
high five!
11
is odd
12
13
is odd
14
is divisable by 14
15
is odd
16
17
is odd
18
19
is odd
20
high five!
21
is odd
22
23
is odd
24
25
is odd
26
27
is odd
28
is divisable by 14
29
is odd
30
high five!
31
is odd
32
this happens twice
33
is odd
34
35
is odd
36
37
is odd
38
39
is odd
40
high five!
this happens twice
41
is odd
42
is divisable by 14
43
is odd
44
45
is odd
46
47
is odd
48
49
is odd
50
high five!
51
is odd
52
53
is odd
54
55
is odd
56
is divisable by 14
57
is odd
58
59
is odd
60
high five!
61
is odd
62
63
is odd
64
65
is odd
66
67
is odd
68
69
is odd
70
is divisable by 14
high five!
71
is odd
72
73
is odd
74
75
is odd
76
77
is odd
78
79
is odd
80
high five!
81
is odd
82
83
is odd
84
is divisable by 14
85
is odd
86
87
is odd
88
89
is odd
90
high five!
91
is odd
92
93
is odd
94
95
is odd
96
97
is odd
98
is divisable by 14
99
is odd
100
high five!

In [25]:
56/14

4.0